### ISSUE TITLE
JSON to CSV converter ignores multiple annotations of each task (LS 1.0)

### ISSUE THREAD

**Issue by uriel-tannen** [heartexlabs/label-studio-converter#28]
This relates to a point discussed with @niklub in the LS Slack workspace. 

If I have a JSON file with multiple annotations of a single task, running the CSV conversion command (e.g. `python backend/converter/cli.py --input examples/sentiment_analysis/completions/ --config examples/sentiment_analysis/config.xml --output output_dir --format CSV --csv-separator $'\t'`) outputs a CSV file with just one line: the most recent annotations. Earlier annotations are not reflected in the CSV. 

I think what would make most sense is for each row in the CSV to be its own task-annotation datapoint(s). So if there were 2 tasks with 2 annotations each, the CSV would have the following rows:

1. header
2. task 1 user/annotation 1
3. task 1 user/annotation 2
4. task 2 user/annotation 1
5. task 2 user/annotation 2

**Comment by makseq** [comment]
@uriel-tannen I hope it's fixed in release/1.0.1 branch. Don't forget to update `label-studio-converter` up to 0.27.0.

**Comment by uriel-tannen** [comment]
@makseq I mentioned this to @niklub on Slack, but I'm using 0.28.0 and still have the following issue:
I tried running the converter on a bunch of JSON files in my S3 bucket, and got the following error: `"Each task dict item should contain "annotations" or "completions" [deprecated], where value is list of dicts"`. Looking through the JSON files in S3, the labels fall under `result` - there is no `annotations` in the file (exporting as a JSON file from the LS front-end, as opposed to those sent to S3, has `result` nested under `annotations`).
